[build-system]
requires = ["scikit-build-core", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "blitz_lib"
version = "0.0.1"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true