# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'generate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egenerate.proto\x12\x0bgenerate.v2\"&\n\x10PullModelRequest\x12\x12\n\nmodel_name\x18\x01 \x02(\t\"\x13\n\x11PullModelResponse\"h\n\x11LoadWeightRequest\x12\x12\n\nipc_handle\x18\x01 \x02(\x0c\x12\x13\n\x0btensor_size\x18\x02 \x02(\x04\x12\x15\n\rtensor_device\x18\x03 \x02(\r\x12\x13\n\x0btensor_name\x18\x04 \x02(\t\"\x14\n\x12LoadWeightResponse2\xad\x01\n\x0cParamService\x12L\n\tPullModel\x12\x1d.generate.v2.PullModelRequest\x1a\x1e.generate.v2.PullModelResponse\"\x00\x12O\n\nLoadWeight\x12\x1e.generate.v2.LoadWeightRequest\x1a\x1f.generate.v2.LoadWeightResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PULLMODELREQUEST']._serialized_start=31
  _globals['_PULLMODELREQUEST']._serialized_end=69
  _globals['_PULLMODELRESPONSE']._serialized_start=71
  _globals['_PULLMODELRESPONSE']._serialized_end=90
  _globals['_LOADWEIGHTREQUEST']._serialized_start=92
  _globals['_LOADWEIGHTREQUEST']._serialized_end=196
  _globals['_LOADWEIGHTRESPONSE']._serialized_start=198
  _globals['_LOADWEIGHTRESPONSE']._serialized_end=218
  _globals['_PARAMSERVICE']._serialized_start=221
  _globals['_PARAMSERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
