# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import generate_pb2 as generate__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in generate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullModel = channel.unary_unary(
                '/generate.v2.ParamService/PullModel',
                request_serializer=generate__pb2.PullModelRequest.SerializeToString,
                response_deserializer=generate__pb2.PullModelResponse.FromString,
                _registered_method=True)
        self.LoadWeight = channel.unary_unary(
                '/generate.v2.ParamService/LoadWeight',
                request_serializer=generate__pb2.LoadWeightRequest.SerializeToString,
                response_deserializer=generate__pb2.LoadWeightResponse.FromString,
                _registered_method=True)
        self.GetHandler = channel.unary_unary(
                '/generate.v2.ParamService/GetHandler',
                request_serializer=generate__pb2.GetHandlerRequest.SerializeToString,
                response_deserializer=generate__pb2.GetHandlerResponse.FromString,
                _registered_method=True)
        self.RevertHandler = channel.unary_unary(
                '/generate.v2.ParamService/RevertHandler',
                request_serializer=generate__pb2.RevertHandlerRequest.SerializeToString,
                response_deserializer=generate__pb2.RevertHandlerResponse.FromString,
                _registered_method=True)


class ParamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PullModel(self, request, context):
        """Request to load model from repo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadWeight(self, request, context):
        """Request to load weights to torch.Tensor, engine returns a shm/gpu ptr, clients to move data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHandler(self, request, context):
        """Request to get c++ memory handler
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevertHandler(self, request, context):
        """Request to inform engine that handler can be destroyed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PullModel,
                    request_deserializer=generate__pb2.PullModelRequest.FromString,
                    response_serializer=generate__pb2.PullModelResponse.SerializeToString,
            ),
            'LoadWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadWeight,
                    request_deserializer=generate__pb2.LoadWeightRequest.FromString,
                    response_serializer=generate__pb2.LoadWeightResponse.SerializeToString,
            ),
            'GetHandler': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHandler,
                    request_deserializer=generate__pb2.GetHandlerRequest.FromString,
                    response_serializer=generate__pb2.GetHandlerResponse.SerializeToString,
            ),
            'RevertHandler': grpc.unary_unary_rpc_method_handler(
                    servicer.RevertHandler,
                    request_deserializer=generate__pb2.RevertHandlerRequest.FromString,
                    response_serializer=generate__pb2.RevertHandlerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generate.v2.ParamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generate.v2.ParamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PullModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generate.v2.ParamService/PullModel',
            generate__pb2.PullModelRequest.SerializeToString,
            generate__pb2.PullModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generate.v2.ParamService/LoadWeight',
            generate__pb2.LoadWeightRequest.SerializeToString,
            generate__pb2.LoadWeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generate.v2.ParamService/GetHandler',
            generate__pb2.GetHandlerRequest.SerializeToString,
            generate__pb2.GetHandlerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevertHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generate.v2.ParamService/RevertHandler',
            generate__pb2.RevertHandlerRequest.SerializeToString,
            generate__pb2.RevertHandlerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
